# Generated by Django 3.2.4 on 2021-06-21 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='scopes',
        ),
        migrations.RenameField(
            model_name='articletag',
            old_name='tag',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='articles',
        ),
    ]
