# Generated by Django 3.2.4 on 2021-06-21 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20210622_0121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.RenameField(
            model_name='articletag',
            old_name='name',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tagname',
            new_name='name',
        ),
    ]
