# Generated by Django 3.2.4 on 2021-06-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210622_0122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletag',
            old_name='tag',
            new_name='name',
        ),
    ]
