# Generated by Django 3.2.4 on 2021-06-21 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_tag_articletag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletag',
            old_name='name',
            new_name='tag',
        ),
    ]
